### PR TITLE
Added migration file

### PR DESCRIPTION
**Pull request by juliuswelby**
I seem to have not moved this forward to the PR. Doing that now.

### CODE REVIEW

**Comment by TomJKing** [comment]
@juliuswelby The build is failing because of this error:

```
Message    : ERROR: insert or update on table "FilePropertyDependencies" violates foreign key constraint "FilePropertyDependencies_PropertyName_FileProperty_fkey"
[error]   Detail: Key (PropertyName)=(TitlePublic) is not present in table "FileProperty".
[error] Location   : lambda/src/main/resources/db/migration/V79__Foreign_key_creation_for_file_property_tables.sql (/home/runner/work/tdr-consignment-api-data/tdr-consignment-api-data/lambda/src/main/resources/db/migration/V79__Foreign_key_creation_for_file_property_tables.sql)
```

**Comment by pashworth-tna** [comment]
@TomJKing I'm looking into this.

**Comment by pashworth-tna** [comment]
Note: this doesn't solve the problem . 
First thought is that I don't think we need we need the unique constraint or fkey for the following
`FilePropertyDependencies_FilePropertyValues_GroupId_fkey"
 The reason being is that whilst we currently have have dependency groups across multiple properties .... it is possible that we might in the future. The Unique constraint would stop that being possible. Therefore I think we should remove the constraint and key lines for it.

**Comment by pashworth-tna** [comment]
@TomJKing As for the error: This is saying that the value TitlePublic is not in the Fileproperty table. 
Script V72 had updated the Fileproperty table changing the value TitlePublic -> TitleClosed however the script did not update the FilePropertyDependencies table at the same time.
This was resolved in script V78 ( i.e. the one before this one. ) 
I've looked at the data in the db and TitlePublic does not exist in either of the tables. So I am a bit confused.
It is almost like V78 is not be run or committed  as part of the migration before V79 is attempted to being run. 

Thoughts???

**Comment by pashworth-tna** [comment]
@TomJKing are you happy for me to remove the last constraint and unique from the script and recommit
??

**Comment by pashworth-tna** [comment]
@TomJKing Script has been updated

**Review by TomJKing — COMMENTED** [review]
Looks good. One very minor comment.

**Comment by pashworth-tna** [comment]
@TomJKing Updated the comment. Sorry. So ready to go.... But I noticed that this script has V79 which is also used by another pull request. I'd be happy to change the VNo for this if you wanted to merge the other first.

**Comment by TomJKing** [comment]
@pashworth-tna If V79 is currently not used on the main branch, then no need to update. Whoever has used in on another PR will need to update before they merge. First come, first served ;)

**Review by TomJKing — APPROVED** [review]

**Pull request merged**
