### PR TITLE
Tdr 715 migration transfer agreement data

### PR DESCRIPTION
**Pull request by TomJKing**
Requires PR: 

- https://github.com/nationalarchives/tdr-consignment-api-data/pull/61
- https://github.com/nationalarchives/tdr-consignment-api/pull/107

Change the API to pipe the Transfer Agreement data to the `ConsignmentMetadata` table first, and then migrate the data from the `TransferAgreement` table to the `ConsignmentMetadata `table. This wil ensure no data get missed in the migration.

### CODE REVIEW

**Comment by suzannehamilton** [comment]
Is this still a draft, or would you like a review?

**Review by suzannehamilton — COMMENTED** [review]
This looks good to me. I think it will have to be renumbered to 23 because #71 was merged first.

**Comment by TomJKing** [comment]
Renumbered. There is something like nearly 9000 TransferAgreement DB rows to migrate in Intg last time I checked. Will this cause issues with running this migration?

**Comment by suzannehamilton** [comment]
My guess is that those won't take too long to migrate, but keep an eye on the migration. It would be useful to know if it is slow!

**Review by suzannehamilton — APPROVED** [review]

**Pull request merged**
