### PR TITLE
Create AllowedPuids and DisallowedPuids table

### PR DESCRIPTION
**Pull request by thanhz**
@pashworth-tna I have filled in the puid description using the `Name` from the summary that I found on the Pronom website for example https://www.nationalarchives.gov.uk/PRONOM/fmt/412.

### CODE REVIEW

**Comment by pashworth-tna** [comment]
Could you make the ConsignmentType Not NULL as it should always be required.
And also the Reason NOT null as that would be required to report on.
And could you just check that there is a new line after the commit... I can't tell if it has one.

**Comment by thanhz** [comment]
> Could you make the ConsignmentType Not NULL as it should always be required. And also the Reason NOT null as that would be required to report on. And could you just check that there is a new line after the commit... I can't tell if it has one.

@pashworth-tna I've made the changes as requested. Yep there is a new line after the commit. :+1:

**Comment by pashworth-tna** [comment]
Just noticed you have the descriptions as NULL...... did you mean not null????

**Comment by pashworth-tna** [comment]
It is also failing Flyway test

**Comment by pashworth-tna** [comment]
And there is a comma after the last statement in each

**Comment by thanhz** [comment]
> Just noticed you have the descriptions as NULL...... did you mean not null????

Hmm @TomJKing suggested this to be NULL but do you think this should be `NOT NULL`?

**Comment by thanhz** [comment]
> And there is a comma after the last statement in each

Yep for some reason it didn't push it the first time. It's fixed now

**Review by pashworth-tna — APPROVED** [review]
Looks ok

**Pull request merged**
