### PR TITLE
TDR-3235 Generate fileStatusId in db 

### PR DESCRIPTION
**Pull request by tna-aford**
- [x] Migration created to generate UUID in database rather than API.  

image

### CODE REVIEW

**Review by TomJKing — COMMENTED** [review]
Looks OK to me.

Would be good if @pashworth-tna could take a look.

**Review by TomJKing — APPROVED** [review]
Looks good. Thanks.

**Review by TomJKing — CHANGES_REQUESTED** [review]
Given we're generating the UUID for the id, we should also generate the `CreatedDatetime` in the DB to be consistent.

This will also reduce the changes required in API.

**Comment by tna-aford** [comment]
image

Change made as requested

**Review by TomJKing — DISMISSED** [review]
Looks good. Thanks

**Review by TomJKing — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
