### PR TITLE
TDR-2526 Add new body "Land Registry"

### PR DESCRIPTION
**Pull request by thanhz**

### CODE REVIEW

**Comment by pashworth-tna** [comment]
Do we have a series to go with this body??? 
It's just easier to add at the same time

**Comment by thanhz** [comment]
> Do we have a series to go with this body??? It's just easier to add at the same time

Ah yes your right Phil. I've added the series now. Tested and its working fine.

**Comment by thanhz** [comment]
> Do we have a series to go with this body??? It's just easier to add at the same time

@pashworth-tna Ah yes, you're right Phil. I've added the series now. Tested and its working fine.

**Comment by pashworth-tna** [comment]
Looks good to me but not sure If I am allowed to approve.

**Review by TomJKing — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
